apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: demo-iac
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: v10.22.0
    helm:
      values: |-
        ports:
          traefik:
            port: 9000
          web:
            nodePort: 30080
          websecure:
            nodePort: 30443
            tls:
              enabled: true
        providers:
          kubernetesIngress:
            publishedService:
              enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

