apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- eventbus.yaml
- eventsource.yaml
- ingress-webhook-eventsource.yaml
- installer-pipeline.yaml
namespace: argo-events
