apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc
  namespace: nautes
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  volumeMode: Filesystem
