apiVersion: v1
kind: Secret
metadata:
  name: github-deploykey
  namespace: nautes
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: <private-key>
